dataset:
  number_classes: 4
  input_size: 224
data_loader:
  train: 
    batch_size: 32
    shuffle: true
    num_workers: 1
    pin_memory: true
  val: 
    batch_size: 16
    shuffle: false
    num_workers: 2
    pin_memory: true
  test:
    batch_size: 16
    shuffle: false
    num_workers: 2
    pin_memory: false
train:
  optimizer:
    name: 'Adam'
    lr: 0.001      
  scheduler:
    factor: 0.5
    patience: 10
  epochs: 200
model:
  save_dir: 'model/'
  params:
    in_channels: 3
    out_channels: 4
    batch_norm: false
    